version: '3'
services:

  data_service:
    container_name: ime_data_service
    image: node:10
    ports:
      - 8080:8081
    volumes:
      - ./src/data-service:/home/node/app

  torre_service:
    container_name: ime_torre_service
    image: node:10
    ports:
      - 8081:8081
    volumes:
      - ./src/torre-service:/home/node/app

  suggestion_service:
    container_name: ime_suggestion_service
    image: node:10
    ports:
      - 8082:8081
    volumes:
      - ./src/suggestion-service:/home/node/app

  redis:
    container_name: ime_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  # postgres:
  #   container_name: fys_postgres
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - 5438:5432
  #   volumes:
  #     - ./data:/var/lib/postgresql/data