version: '3'
services:
  api:
    container_name: fys_api
    image: nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 8088:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  redis:
    container_name: ime_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  # postgres:
  #   container_name: fys_postgres
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - 5438:5432
  #   volumes:
  #     - ./data:/var/lib/postgresql/data